Fix #19644: Remove user role from UI, redisplay list of users in the event of a backend failure (#20201)
* Make a copy of the list of users prior to deletion in the event of an error response from the backend.

* Remove user from list of users as soon as delete action is confirmed on the frontend.

* Redisplay list of users based on values prior to deletion attempt using the copy made earlier and display error message to end user.

* Test if user is removed from UI before updating with backend data.

* Test if user is removed from UI before updating with backend data.

* Test if user is redisplayed when an error occurs from backend.

* Fix Beam Jobs Tab async timeout errors.

* Address review comment: modify code to only remove user from its specific list, and only add back user to its specific list on failure.

* Address review comment: Fix unit tests.

* Display success message to user upon successful deletion.

* remove async timeout change

* Fix linter errors

* fix compilation errors

* Address review comment: Generalize the code for removing user from its category and adding a user back to its category on failure

* Fix unit test to expect fail handler to be called on failure and verify state of each category

* Fix compile errors

* fix compile issues

* Fix compilation issues

* Address review comment: store the category for which user is removed from, use as a reference in catch block

* Address review comments: fix unit tests and change variable name

* Fix TypeError issues